# nixpacks.toml
[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['cd apps/web && npm install']

[phases.build]
cmds = ['cd apps/web && npm run build']

[start]
cmd = 'cd apps/web && npx serve -s dist -l 8080'
